<a href="https://colab.research.google.com/github/iwinjoseph03/ANN_22AIP3204/blob/main/notebooks/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [39]:

iris=load_iris()


In [41]:
x=iris.data
y=iris.target

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=25)
scaler=StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [ ]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=1000,random_state=42)

In [ ]:
mlp.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000, random_state=42)

In [ ]:
y_predict=mlp.predict(x_test)

In [ ]:
print(y_predict)

[0 1 2 1 2 1 2 0 1 1 0 0 0 1 0 1 2 2 1 1 1 1 1 0 0 2 1 2 2 0 1 2 2 0 2 1 2
 0 0 0 0 0 0 0 2]


In [42]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier



In [43]:
iris=load_iris()
x=iris.data
y=iris.target

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)

In [46]:
scaler=StandardScaler()

In [47]:
scaler.fit(x_train)

StandardScaler()

In [48]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [49]:
mlp=MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=1000,random_state=25)

In [50]:
mlp.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000, random_state=25)

In [51]:
y_predict=mlp.predict(x_test)

In [52]:
print(y_predict)

[0 1 1 1 2 1 2 0 1 1 0 0 0 1 0 1 2 2 1 1 1 1 1 0 0 2 1 2 2 1 1 2 2 0 2 1 1
 0 0 0 0 0 0 0 2]


In [53]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

In [54]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)

In [55]:
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [56]:
mlp=MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=1000,random_state=25)

In [57]:
mlp.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000, random_state=25)

In [58]:
y_predict=mlp.predict(x_test)

In [60]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_predict,y_test))
print(classification_report(y_predict,y_test))


[[16  0  0]
 [ 1 16  1]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        16
           1       1.00      0.89      0.94        18
           2       0.92      1.00      0.96        11

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [59]:
print(y_predict)

[0 1 1 1 2 1 2 0 1 1 0 0 0 1 0 1 2 2 1 1 1 1 1 0 0 2 1 2 2 1 1 2 2 0 2 1 1
 0 0 0 0 0 0 0 2]


In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
iris = load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
mlp=MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=1000,random_state=25)
mlp.fit(x_train,y_train)
y_predict=mlp.predict(x_test)

In [64]:
print(y_predict)

[0 1 1 1 2 1 2 0 1 1 0 0 0 1 0 1 2 2 1 1 1 1 1 0 0 2 1 2 2 1 1 2 2 0 2 1 1
 0 0 0 0 0 0 0 2]


In [14]:
ir=pd.read_csv('/content/Iris.csv')

In [15]:
ir.shape

(150, 6)

In [17]:
ir.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [18]:
ir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [8]:
ir.value_counts(Species)

NameError: name 'Species' is not defined

In [10]:
ir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [11]:
ir.shape

(150, 6)

In [13]:
ir.value_counts('Species')

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64